#!/usr/bin/env python3
#
# normalize-asn-records
# Kenneth Finnegan, 2018
# 
# Given resource allocation records, this script expands compressed asn
# lines into each individual asn
#
# The issue is that in the specified CSV format, when multiple ASNs have
# identical records they're compressed into the first ASN plus a count of
# how many ASNs in a row there are.
#
# Example records, the second of which should be expanded into three lines:
# afrinic|ZZ|asn|37291|1||available|
# afrinic|BJ|asn|37292|3|20110225|allocated|F36BC33B
#
# The main reason for this normalization is to make it easier to look up
# specific ASN records without needing to parse this compression format.

import sys

for record_in in sys.stdin:
	record_list = record_in.split('|')

	if record_list[2] != 'asn':
		print('|'.join(record_list), end='')
		continue

	for asn_offset in range(int(record_list[4])):
		record_out = record_list.copy()
		record_out[3] = str(int(record_list[3]) + asn_offset)
		record_out[4] = '1'
		print('|'.join(record_out), end='')
